
package com.techiekernel.ws.jaxws.mtom;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "FileImageServer", targetNamespace = "http://mtom.jaxws.ws.techiekernel.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FileImageServer {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "uploadImage", targetNamespace = "http://mtom.jaxws.ws.techiekernel.com/", className = "com.techiekernel.ws.jaxws.mtom.UploadImage")
    @ResponseWrapper(localName = "uploadImageResponse", targetNamespace = "http://mtom.jaxws.ws.techiekernel.com/", className = "com.techiekernel.ws.jaxws.mtom.UploadImageResponse")
    public String uploadImage(
        @WebParam(name = "arg0", targetNamespace = "")
        byte[] arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns byte[]
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "downloadImage", targetNamespace = "http://mtom.jaxws.ws.techiekernel.com/", className = "com.techiekernel.ws.jaxws.mtom.DownloadImage")
    @ResponseWrapper(localName = "downloadImageResponse", targetNamespace = "http://mtom.jaxws.ws.techiekernel.com/", className = "com.techiekernel.ws.jaxws.mtom.DownloadImageResponse")
    public byte[] downloadImage(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
