
package com.techiekernel.ws.jaxws.mtom;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "FileImageServerService", targetNamespace = "http://mtom.jaxws.ws.techiekernel.com/", wsdlLocation = "http://localhost:8080/webservice-JAX-WS-handler/fileImageServer?wsdl")
public class FileImageServerService
    extends Service
{

    private final static URL FILEIMAGESERVERSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.techiekernel.ws.jaxws.mtom.FileImageServerService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.techiekernel.ws.jaxws.mtom.FileImageServerService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/webservice-JAX-WS-handler/fileImageServer?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/webservice-JAX-WS-handler/fileImageServer?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        FILEIMAGESERVERSERVICE_WSDL_LOCATION = url;
    }

    public FileImageServerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FileImageServerService() {
        super(FILEIMAGESERVERSERVICE_WSDL_LOCATION, new QName("http://mtom.jaxws.ws.techiekernel.com/", "FileImageServerService"));
    }

    /**
     * 
     * @return
     *     returns FileImageServer
     */
    @WebEndpoint(name = "FileImageServerPort")
    public FileImageServer getFileImageServerPort() {
        return super.getPort(new QName("http://mtom.jaxws.ws.techiekernel.com/", "FileImageServerPort"), FileImageServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FileImageServer
     */
    @WebEndpoint(name = "FileImageServerPort")
    public FileImageServer getFileImageServerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://mtom.jaxws.ws.techiekernel.com/", "FileImageServerPort"), FileImageServer.class, features);
    }

}
